<?php

namespace App\Console\Commands;

use App\Support\Shell;
use Illuminate\Console\Command;

/**
 * CHANGELOG.md from the tags. Released sections that already exist in the file are kept verbatim
 * (so they can be edited by hand); missing ones are generated from `git log prev..tag`; the
 * Unreleased section is always regenerated from `latest..HEAD`. Running it twice is a no-op.
 */
class DocsChangelogCommand extends Command
{
    protected $signature = 'docs:changelog
        {--out=CHANGELOG.md : where to write, relative to the app root}
        {--stdout : print instead of writing}
        {--next= : label the Unreleased section as this version (used when tagging, e.g. --next=2.0.0)}';

    protected $description = 'Regenerate CHANGELOG.md from git tags; keeps sections you have edited';

    private const HEADER = "# Changelog\n\nAll notable changes to nomeus. The format follows [Keep a Changelog](https://keepachangelog.com/en/1.1.0/);\nversions are the git tags. Generated by `nomeus docs:changelog` — released sections can be edited by hand and are kept;\nthe Unreleased section is rebuilt on every run.\n\n";

    public function handle(Shell $shell): int
    {
        $root = base_path();

        $tags = $this->tags($shell, $root);
        if ($tags === []) {
            $this->error('no tags found — nothing to write');

            return self::FAILURE;
        }

        $out = (string) $this->option('out');
        $out = str_starts_with($out, '/') ? $out : $root.'/'.$out;
        $existing = is_file($out) ? $this->sections((string) file_get_contents($out)) : [];

        $md = self::HEADER;

        // Unreleased: always from git, never from the file.
        $latest = $tags[0]['name'];
        $unreleased = $this->subjects($shell, $root, "{$latest}..HEAD");
        $next = $this->option('next') ? ltrim((string) $this->option('next'), 'v') : null;
        $tagged = array_map(fn (array $t) => ltrim($t['name'], 'v'), $tags);
        $pending = array_values(array_diff(array_keys($existing), $tagged));   // a section written with --next, not yet tagged
        if ($next !== null) {
            $md .= $this->section($next, date('Y-m-d'), $unreleased ?: ['No changes recorded since '.$latest.'.'], $latest, 'v'.$next);
        } elseif ($pending !== []) {
            foreach ($pending as $version) {
                $md .= $existing[$version];
            }
        } elseif ($unreleased !== []) {
            $md .= $this->section('Unreleased', null, $unreleased, $latest, null);
        }

        $generated = 0;
        foreach ($tags as $i => $tag) {
            $version = ltrim($tag['name'], 'v');
            if (isset($existing[$version])) {
                $md .= $existing[$version];

                continue;
            }
            $prev = $tags[$i + 1]['name'] ?? null;
            $range = $prev ? "{$prev}..{$tag['name']}" : $tag['name'];
            $md .= $this->section($version, $tag['date'], $this->subjects($shell, $root, $range) ?: ['Initial release.'], $prev, $tag['name']);
            $generated++;
        }

        $md = rtrim($md)."\n";

        if ($this->option('stdout')) {
            $this->line($md);

            return self::SUCCESS;
        }
        file_put_contents($out, $md);
        $this->info("wrote {$out} (".count($tags).' releases, '.$generated.' generated, '.(count($tags) - $generated).' kept)');

        return self::SUCCESS;
    }

    /** [['name' => 'v1.12.0', 'date' => '2026-09-03'], …] newest first. */
    private function tags(Shell $shell, string $root): array
    {
        $result = $shell->run(['git', 'for-each-ref', '--sort=-version:refname', '--format=%(refname:short) %(creatordate:short)', 'refs/tags/v*'], $root, 20);
        if (! $result->successful()) {
            return [];
        }
        $tags = [];
        foreach (preg_split('/\R/', trim($result->output())) ?: [] as $line) {
            if (preg_match('/^(v\d+\.\d+\.\d+)\s+(\d{4}-\d{2}-\d{2})$/', trim($line), $m)) {
                $tags[] = ['name' => $m[1], 'date' => $m[2]];
            }
        }

        return $tags;
    }

    /** Commit subjects for a range, oldest first, duplicates and merge/noise subjects dropped. */
    private function subjects(Shell $shell, string $root, string $range): array
    {
        $result = $shell->run(['git', 'log', '--reverse', '--no-merges', '--format=%s', $range], $root, 20);
        if (! $result->successful()) {
            return [];
        }
        $seen = [];
        $out = [];
        foreach (preg_split('/\R/', trim($result->output())) ?: [] as $subject) {
            $subject = trim($subject);
            if ($subject === '' || isset($seen[$subject]) || preg_match('/^(fresh|wip|Create CNAME|Update .*\.md)$/i', $subject)) {
                continue;
            }
            $seen[$subject] = true;
            $out[] = $subject;
        }

        return $out;
    }

    private function section(string $version, ?string $date, array $bullets, ?string $from, ?string $to): string
    {
        $title = $date ? "## [{$version}] - {$date}" : "## [{$version}]";
        if ($from !== null) {
            $compare = 'https://github.com/owldesign/nomeus/compare/'.$from.'...'.($to ?? 'HEAD');
            $title = str_replace("[{$version}]", "[{$version}]({$compare})", $title);
        }
        $body = implode("\n", array_map(fn (string $b) => '- '.$this->escape($b), $bullets));

        return "{$title}\n\n{$body}\n\n";
    }

    /** Commit subjects use `slice: text`; keep them readable in Markdown without turning `<` into HTML. */
    private function escape(string $s): string
    {
        return str_replace(['<', '>'], ['\<', '\>'], $s);
    }

    /** Existing released sections keyed by version, each block verbatim (header through the blank line before the next). */
    private function sections(string $md): array
    {
        $blocks = [];
        if (! preg_match_all('/^## \[([^\]]+)\][^\n]*\n(?:(?!^## ).*\n?)*/m', $md, $m, PREG_SET_ORDER)) {
            return $blocks;
        }
        foreach ($m as $match) {
            $version = $match[1];
            if ($version === 'Unreleased' || ! preg_match('/^\d+\.\d+\.\d+$/', $version)) {
                continue;
            }
            $blocks[$version] = rtrim($match[0])."\n\n";
        }

        return $blocks;
    }
}
