<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Artisan;
use Symfony\Component\Console\Input\InputOption;

/** docs/commands.md from the real command list, so the reference cannot drift from the code. */
class DocsCommandsCommand extends Command
{
    protected $signature = 'docs:commands {--out=docs/commands.md} {--stdout}';

    protected $description = 'Regenerate docs/commands.md from the registered nomeus commands';

    public function handle(): int
    {
        $groups = [];
        foreach (Artisan::all() as $name => $command) {
            if (! str_starts_with(get_class($command), 'App\\Console\\Commands')) {
                continue;
            }
            $group = str_contains($name, ':') ? strtok($name, ':') : 'general';
            $groups[$group][$name] = $command;
        }
        ksort($groups);

        $md = "# nomeus commands\n\nGenerated by `nomeus docs:commands` — edit the commands, not this file.\n\n";
        foreach ($groups as $group => $commands) {
            ksort($commands);
            $md .= "## {$group}\n\n";
            foreach ($commands as $name => $command) {
                $def = $command->getNativeDefinition();
                $sig = $name;
                foreach ($def->getArguments() as $arg) {
                    $sig .= ' '.($arg->isRequired() ? "<{$arg->getName()}>" : "[{$arg->getName()}]");
                }
                foreach ($def->getOptions() as $opt) {
                    $sig .= ' [--'.$opt->getName().($opt->acceptValue() ? '='.($opt->isArray() ? '*' : $this->default($opt)) : '').']';
                }
                $md .= "### `{$sig}`\n\n{$command->getDescription()}\n\n";
                $lines = [];
                foreach ($def->getArguments() as $arg) {
                    if ($arg->getDescription()) {
                        $lines[] = "- `{$arg->getName()}` — {$arg->getDescription()}";
                    }
                }
                foreach ($def->getOptions() as $opt) {
                    if ($opt->getDescription()) {
                        $default = $opt->isArray() ? '' : $this->default($opt);
                        $lines[] = "- `--{$opt->getName()}".($default !== '' ? "={$default}" : '')."` — {$opt->getDescription()}";
                    }
                }
                if ($lines) {
                    $md .= implode("\n", $lines)."\n\n";
                }
            }
        }

        if ($this->option('stdout')) {
            $this->line($md);

            return self::SUCCESS;
        }
        $out = (string) $this->option('out');
        $out = str_starts_with($out, '/') ? $out : base_path($out);
        if (! is_dir(dirname($out))) {
            mkdir(dirname($out), 0755, true);
        }
        file_put_contents($out, $md);
        $this->info("wrote {$out} (".count(array_merge(...array_map('array_keys', array_values($groups)))).' commands)');

        return self::SUCCESS;
    }

    /** A scalar default worth showing (`--lines=50`); '' when there is none. Must be deterministic across machines. */
    private function default(InputOption $opt): string
    {
        $d = $opt->getDefault();

        return is_scalar($d) && $d !== false && (string) $d !== '' ? (string) $d : '';
    }
}
