<?php

namespace App\Services\New;

use App\Services\Services\DriverRegistry;
use App\Services\ServiceManager;
use Illuminate\Support\Str;
use Symfony\Component\Yaml\Yaml;

/**
 * Answers → nomeus.yml. Picks the instances you already have (a postgres request becomes
 * `instance: pg17`, not a new cluster) and names the database/bucket after the site.
 */
final class ManifestBuilder
{
    public const DATABASES = ['postgresql', 'mysql', 'mariadb'];

    public function __construct(private readonly ServiceManager $services, private readonly DriverRegistry $drivers) {}

    /**
     * @param  array{name:string, domain?:string, php?:?string, node?:?string, secure?:bool, services?:list<string>, mail?:bool,
     *               env?:array<string,string>, post_init?:list<string>}  $a
     */
    public function build(array $a): array
    {
        $name = $a['name'];
        $slug = Str::slug($name, '_');
        $out = ['name' => $name, 'domain' => $a['domain'] ?? Str::slug($name)];
        if (! empty($a['php'])) {
            $out['php'] = (string) $a['php'];
        }
        if (! empty($a['node'])) {
            $out['node'] = (string) $a['node'];
        }
        if (! empty($a['secure'])) {
            $out['secure'] = true;
        }

        $services = [];
        foreach ($a['services'] ?? [] as $type) {
            if (! $this->drivers->has($type)) {
                continue;
            }
            $entry = ['type' => $type];
            if ($instance = $this->instanceFor($type)) {
                $entry['instance'] = $instance;
            }
            if (in_array($type, self::DATABASES, true)) {
                $entry['database'] = $slug;
            } elseif ($type === 'seaweedfs') {
                $entry['bucket'] = Str::slug($name);
            }
            $services[] = $entry;
        }
        if ($services !== []) {
            $out['services'] = $services;
        }
        if (! empty($a['mail'])) {
            $out['mail'] = true;
        }
        if (! empty($a['env'])) {
            $out['env'] = $a['env'];
        }
        if (! empty($a['post_init'])) {
            $out['post-init'] = array_values($a['post_init']);
        }

        return $out;
    }

    public function yaml(array $a): string
    {
        $data = $this->build($a);
        // one-line service entries read better in a hand-edited file
        $yaml = "# nomeus.yml — generated by `nomeus new`; edit freely, then `nomeus init`\n";
        $services = $data['services'] ?? null;
        unset($data['services']);
        $yaml .= Yaml::dump($data, 4, 2);
        if ($services) {
            $yaml .= "services:\n";
            foreach ($services as $s) {
                $yaml .= '  - '.Yaml::dump($s, 0)."\n";
            }
        }

        return $yaml;
    }

    /** First existing instance of the type, or null (init will create one). */
    public function instanceFor(string $type): ?string
    {
        foreach ($this->services->all() as $i) {
            if ($i->type === $type) {
                return $i->name;
            }
        }

        return null;
    }
}
