<?php

use App\Services\New\ManifestBuilder;
use App\Services\Services\DriverRegistry;
use Symfony\Component\Yaml\Yaml;
use Tests\Support\FakeServicesWorld;

beforeEach(function () {
    $this->w = new FakeServicesWorld;
    $this->w->manager->create('postgresql', null, 'pg17', start: false);
    $this->builder = new ManifestBuilder($this->w->manager, new DriverRegistry);
});

afterEach(fn () => $this->w->destroy());

it('turns answers into a manifest that reuses existing instances and names the database after the site', function () {
    $data = $this->builder->build([
        'name' => 'shop', 'php' => '8.4', 'secure' => true, 'services' => ['postgresql', 'redis', 'seaweedfs', 'bogus'], 'mail' => true,
        'env' => ['QUEUE_CONNECTION' => 'redis'], 'post_init' => ['php artisan migrate --force'],
    ]);

    expect($data)->toBe([
        'name' => 'shop', 'domain' => 'shop', 'php' => '8.4', 'secure' => true,
        'services' => [
            ['type' => 'postgresql', 'instance' => 'pg17', 'database' => 'shop'],
            ['type' => 'redis'],                                                       // none yet → init creates one
            ['type' => 'seaweedfs', 'bucket' => 'shop'],
        ],
        'mail' => true,
        'env' => ['QUEUE_CONNECTION' => 'redis'],
        'post-init' => ['php artisan migrate --force'],
    ]);
    expect($this->builder->build(['name' => 'My Shop']))->toBe(['name' => 'My Shop', 'domain' => 'my-shop']);
});

it('renders yaml with one-line service entries', function () {
    $yaml = $this->builder->yaml(['name' => 'shop', 'services' => ['postgresql', 'redis'], 'mail' => true]);

    expect($yaml)->toStartWith('# nomeus.yml — generated by `nomeus new`')
        ->and($yaml)->toContain("name: shop\ndomain: shop\nmail: true\n")
        ->and($yaml)->toContain("services:\n  - { type: postgresql, instance: pg17, database: shop }\n  - { type: redis }\n");
    expect(Yaml::parse($yaml)['services'][0]['instance'])->toBe('pg17');   // round-trips
});
