<?php
// nomeus — auto_prepend_file for every PHP process on this machine.
// Regenerated by `nomeus dumps:install`; edits are lost. Cost when capture is off: one file_exists().
//
// When ~/.nomeus/dumps/capture exists, Symfony VarDumper (dump(), dd()) is told to send to nomeus's
// dump server instead of the browser/terminal — it falls back to normal output if nothing listens.
// NOMEUS_DUMP_SERVER also switches on nomeus/client's recorders (queries, jobs, views, …).
if (! isset($_SERVER['NOMEUS_DUMP_SERVER']) && @file_exists('{{FLAG}}')) {
    $_SERVER['VAR_DUMPER_FORMAT'] = 'server';
    $_SERVER['VAR_DUMPER_SERVER'] = '{{HOST}}';
    $_SERVER['NOMEUS_DUMP_SERVER'] = '{{HOST}}';
    $_SERVER['NOMEUS_REQUEST_ID'] = bin2hex(random_bytes(6));
}
