<?php
// devkit — auto_prepend_file for every PHP process on this machine.
// Regenerated by `devkit dumps:install`; edits are lost. Cost when capture is off: one file_exists().
//
// When ~/.devkit/dumps/capture exists, Symfony VarDumper (dump(), dd()) is told to send to devkit's
// dump server instead of the browser/terminal — it falls back to normal output if nothing listens.
// DEVKIT_DUMP_SERVER also switches on zhuk/devkit-client's recorders (queries, jobs, views, …).
if (! isset($_SERVER['DEVKIT_DUMP_SERVER']) && @file_exists('{{FLAG}}')) {
    $_SERVER['VAR_DUMPER_FORMAT'] = 'server';
    $_SERVER['VAR_DUMPER_SERVER'] = '{{HOST}}';
    $_SERVER['DEVKIT_DUMP_SERVER'] = '{{HOST}}';
    $_SERVER['DEVKIT_REQUEST_ID'] = bin2hex(random_bytes(6));
}
