<?php

namespace App\Services\Dumps;

use App\Services\BrewBridge;
use App\Support\DevkitConfig;
use App\Support\Shell;
use RuntimeException;

/**
 * The generated prepend file and the 99-devkit.ini that loads it in every installed PHP version.
 * php-fpm reads ini files at start, so a new ini needs one `valet restart php`; the CLI sees it at once.
 */
final class PrependInstaller
{
    public const INI = '99-devkit.ini';

    public function __construct(
        private readonly DevkitConfig $config,
        private readonly BrewBridge $brew,
        private readonly CaptureFlag $flag,
        private readonly Shell $shell,
    ) {}

    public function prependPath(): string
    {
        return $this->config->dir().'/php/prepend.php';
    }

    public function iniPath(string $version): string
    {
        return $this->brew->prefix()."/etc/php/{$version}/conf.d/".self::INI;
    }

    public function host(): string
    {
        return '127.0.0.1:'.(int) $this->config->get('dumps.port', 9912);
    }

    /** What the prepend file must contain right now. */
    public function prependSource(): string
    {
        $stub = (string) file_get_contents(base_path('resources/php/prepend.stub.php'));

        return str_replace(['{{FLAG}}', '{{HOST}}'], [addslashes($this->flag->path()), $this->host()], $stub);
    }

    public function iniSource(): string
    {
        return "; devkit — regenerated by `devkit dumps:install`; edits are lost.\n"
            ."auto_prepend_file={$this->prependPath()}\n";
    }

    /**
     * @return array{prepend:string, written:list<string>, unchanged:list<string>, versions:list<string>}
     */
    public function install(): array
    {
        $prepend = $this->prependPath();
        if (! is_dir(dirname($prepend))) {
            mkdir(dirname($prepend), 0755, true);
        }
        $this->write($prepend, $this->prependSource());

        $written = [];
        $unchanged = [];
        foreach ($this->brew->installedPhp() as $version) {
            $ini = $this->iniPath($version);
            if (! is_dir(dirname($ini))) {
                throw new RuntimeException("php@{$version} has no conf.d at ".dirname($ini));
            }
            if (is_file($ini) && file_get_contents($ini) === $this->iniSource()) {
                $unchanged[] = $version;
                continue;
            }
            $this->write($ini, $this->iniSource());
            $written[] = $version;
        }

        return ['prepend' => $prepend, 'written' => $written, 'unchanged' => $unchanged, 'versions' => $this->brew->installedPhp()];
    }

    /** @return array<string, array{ini:bool, current:bool}> per installed version */
    public function status(): array
    {
        $out = [];
        foreach ($this->brew->installedPhp() as $version) {
            $ini = $this->iniPath($version);
            $out[$version] = ['ini' => is_file($ini), 'current' => is_file($ini) && file_get_contents($ini) === $this->iniSource()];
        }

        return $out;
    }

    public function prependCurrent(): bool
    {
        return is_file($this->prependPath()) && file_get_contents($this->prependPath()) === $this->prependSource();
    }

    /** `valet restart php` — all versions' fpm daemons, through valet's sudoers. */
    public function restartPlan(): array
    {
        return ['label' => 'valet restart php', 'argv' => [$this->shell->valetBin(), 'restart', 'php'], 'cwd' => null, 'timeout' => 120];
    }

    private function write(string $path, string $content): void
    {
        if (file_put_contents($path, $content) === false) {
            throw new RuntimeException("Could not write {$path}");
        }
    }
}
