<?php

namespace App\Services\Php;

/**
 * Renders nomeus's one ini file per PHP version (99-nomeus.ini) from two independent inputs:
 * the prepend path (dumps) and the xdebug state. Whoever changes either input regenerates the
 * whole file, so neither feature can clobber the other's lines.
 */
final class IniManager
{
    public const FILE = '99-nomeus.ini';

    public function __construct(private readonly int $xdebugPort = 9003) {}

    /**
     * @param  array{so:string, mode:string}|null  $xdebug  null = xdebug not managed for this version
     */
    public function render(?string $prependPath, ?array $xdebug): string
    {
        $out = "; nomeus — regenerated by nomeus (dumps:install, xdebug:mode); edits are lost.\n";

        $out .= "\n; [prepend] dump capture — nomeus dumps:install\n";
        $out .= $prependPath !== null ? "auto_prepend_file={$prependPath}\n" : "; (not installed)\n";

        $out .= "\n; [xdebug] nomeus xdebug:mode\n";
        if ($xdebug === null) {
            $out .= "; (not installed)\n";
        } elseif ($xdebug['mode'] === 'off') {
            $out .= "; mode: off — extension not loaded (zero cost)\n";
        } else {
            $start = $xdebug['mode'] === 'on' ? 'yes' : 'trigger';
            $out .= "; mode: {$xdebug['mode']}\n";
            $out .= "zend_extension={$xdebug['so']}\n";
            $out .= "xdebug.mode=debug,develop\n";
            $out .= "xdebug.start_with_request={$start}\n";
            $out .= "xdebug.client_host=127.0.0.1\n";
            $out .= "xdebug.client_port={$this->xdebugPort}\n";
            $out .= "xdebug.discover_client_host=false\n";
            $out .= "xdebug.log_level=0\n";
        }

        return $out;
    }

    /** What an existing file says its xdebug mode is (null when the section says not installed / file absent). */
    public static function modeIn(string $ini): ?string
    {
        return preg_match('/^; mode: (off|on|trigger)/m', $ini, $m) ? $m[1] : null;
    }
}
